### PR TITLE
Sean bug fixes

### LINKED ISSUE #204: Credit card with very high credit limit shows incorrect output
**Reproduction:** Execute the following command:
- `add /cc /n BPI /cb 4.0 /cl 100000000000000000000001`
Then, list all credit cards.

**Expected outcome:** The line corresponding to this credit card should say
```
BPI [Cashback: 4.00%] [Cashback gained: $0.00] [Card limit: $100000000000000000000001.00] [Balance left: $100000000000000000000001.00]
```

**Actual outcome:** The value displayed for the card limit (and remaning balance) is `99999997781963080000000.00` In addition,
paying with this credit card for some small amounts fails to update the balance:
image

### PR DESCRIPTION
**Pull request by SeanHoWB**
Fixes #204, #209 , #179, #180, #181

### CODE REVIEW

File: src/main/java/seedu/mindmymoney/helper/AddCommandInputTests.java [hunk 1]
```diff
@@ -264,6 +264,13 @@ public static void testCreditCardLimit(String inputLimit) throws MindMyMoneyExce
             throw new MindMyMoneyException("Limit amount must be more than 0");
         }
         assert inputAmountAsDouble > 0 : "Limit amount should have a positive value";
+
+        if (inputAmountAsDouble > 50000) {
```
Comment (danbaterisna) [inline src/main/java/seedu/mindmymoney/helper/AddCommandInputTests.java:268]: If you intend to throw an error when the limit amount is at least 50,000, then should this be `>=`?

Comment (SeanHoWB) [reply src/main/java/seedu/mindmymoney/helper/AddCommandInputTests.java]: meant to be more than 50k, fixed thanks
